---
## set hostname from inventory or ip address if not available
- name: Ensure hostname set
  hostname: name={{ inventory_hostname }}
  when: not inventory_hostname is match('(\d{1,3}\.){3}\d{1,3}')

## manage host file
- name: hosts file frontend entry
  lineinfile:
    path: /etc/hosts
    regexp: 'frontend'
    line: "{{ frontend_ip }} frontend"
    owner: root
    group: root
    mode: 0644
  tags: [configuration, file, hosts]

- name: hosts file backend1 entry
  lineinfile:
    path: /etc/hosts
    regexp: 'backend1'
    line: "{{ backend1_ip }} backend1"
    owner: root
    group: root
    mode: 0644
  tags: [configuration, file, hosts]


- name: hosts file backend2 entry
  lineinfile:
    path: /etc/hosts
    regexp: 'backend2'
    line: "{{ backend2_ip }} backend2"
    owner: root
    group: root
    mode: 0644
  tags: [configuration, file, hosts]
